export { config } from './config'
export { ProjectDetector } from './detector'
export * from './detectors'
export { ProjectDetectorFactory } from './factory'
export { CommandManager } from './manager'
